services:
  postgres:
    image: postgres:18
    container_name: postgres
    ports:
      - '127.0.0.1:${DB_PORT}:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-catalog-db.sh:/docker-entrypoint-initdb.d/init-catalog-db.sh:ro
    networks:
      - mainnet
  
  app:
    build:
      context: .
      target: build
    entrypoint: sh entrypoint.sh
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      WAIT_FOR_DB: 1
    ports:
      - "${APP_PORT}:80"
    networks:
      - mainnet
    depends_on:
      - postgres
    command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80"]

volumes:
  postgres_data:

networks:
  mainnet:
    driver: bridge
